version: 2

# dbt schema = bigquery dataset
# dbt identifier = bigquery table

sources:
  - name: raw
    schema: raw_data_circle
    tables:
      - name: sales
        identifier: raw_cc_sales
      - name: stock
        identifier: raw_cc_stock
      - name: parcel
        identifier: raw_cc_parcel
      - name: parcel_product
        identifier: raw_cc_parcel_product
